[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*Using `httpx` with `starlette\.testclient`.*:Warning
    ignore:.*Using `httpx` with `starlette\.testclient`.*:UserWarning
    ignore:.*Using `httpx` with `starlette\.testclient`.*
